name: Build Failure Prediction

on: [push]

jobs:
  predict:
    runs-on: ubuntu-latest
    outputs:
      prediction: ${{ steps.predict_step.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Build Failure Prediction
        id: predict_step
        run: |
          PREDICTION_RESULT=$(python predict.py)
          echo "result=$PREDICTION_RESULT" >> "$GITHUB_OUTPUT"
          echo "Model Prediction: $PREDICTION_RESULT"

  build:
    runs-on: ubuntu-latest
    needs: predict
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Display Prediction
        run: echo "The model predicted this build would ${{ needs.predict.outputs.prediction }}"

      - name: Build with Maven
        run: ./mvnw package