name: Generate Build Data

on: [push]

jobs:
  generate_data:
    runs-on: ubuntu-latest
    # --- IMPORTANT: Add permissions to read repository metadata and actions history ---
    permissions:
      contents: read
      actions: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch full history for accurate age and interval calculations
          fetch-depth: 0

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Data Collection Script
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }} # Pass the branch name
        run: python predict.py

      - name: Upload Test Data CSV
        uses: actions/upload-artifact@v4
        with:
          name: collected-build-data
          path: ./*.csv